#!/bin/bash
if [ "$#" -ne 2 ] || ! [ -d "$1" ]; then
  echo "Usage: umlparser <source folder> <output file name>"
  echo "Example: umlparser /uml-parser-test-3 output.png"
fi

IN="$1"
OUT="$2"


echo "$IN" "$OUT"

